### PR TITLE
#37 Flip received emit logic so it works on Linux as well

### PR DESCRIPTION
**Pull request by labboy0276**

### CODE REVIEW

**Review by glawson — DISMISSED** [review]

**Comment by glawson** [comment]
LGTM - thanks @labboy0276

**Comment by glawson** [comment]
@labboy0276 - forgot, using  [semantic-release](https://semantic-release.gitbook.io/) with this project.  Please prefix your commit message with `fix:` and push the commit to this PR/. Ty Ty

**Comment by labboy0276** [comment]
@glawson ok i adjusted the commit message

**Review by glawson — APPROVED** [review]

**Pull request merged**
